In [1]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import os
from tensorflow.keras.preprocessing import image
from zipfile import ZipFile 

from PIL import Image

import keras

# importing libraries for Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from sklearn.model_selection import GridSearchCV
from keras.models import load_model

from keras.models import model_from_json
from keras.wrappers.scikit_learn import KerasClassifier

import PIL
from keras.wrappers.scikit_learn import KerasClassifier

Using TensorFlow backend.


In [2]:

train_dir_walls = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/train_300/walls'
train_dir_underpass = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/train_300/underpass'
test_dir_walls = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/test_300/walls'
test_dir_underpass = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/test_300/underpass'

In [3]:
train_dir="C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/train_300"
test_dir="C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/test_300"

In [4]:
print('number of walls training images - ',len(os.listdir(train_dir_walls)))
print('number of underpasss training images - ',len(os.listdir(train_dir_underpass)))
print('number of walls testing images - ',len(os.listdir(test_dir_walls)))
print('number of underpass testing images - ',len(os.listdir(test_dir_underpass)))

number of walls training images -  325
number of underpasss training images -  339
number of walls testing images -  76
number of underpass testing images -  72


In [5]:
data_generator = ImageDataGenerator(rescale = 1.0/255.0,zoom_range= 0.1)

In [6]:
batch_size = 20

training_data = data_generator.flow_from_directory(directory = train_dir,target_size = (100, 100),
                                                   batch_size = batch_size,class_mode = 'binary')

testing_data = data_generator.flow_from_directory(directory = test_dir,target_size = (100, 100),
                                                  batch_size = batch_size,class_mode = 'binary')

print(training_data.classes)

Found 664 images belonging to 2 classes.
Found 148 images belonging to 2 classes.
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1

#GridSearchCv

def make_model(optimizer='rmsprop', init='glorot_uniform'):
    model = Sequential()

    model.add(Conv2D(filters = 64, kernel_size = (5, 5), activation = 'relu', input_shape = training_data.image_shape))
    model.add(MaxPooling2D(pool_size = (4, 4)))
    model.add(Dropout(rate = 0.4))

    model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    #model.add(Dropout(rate = 0.2))

    model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2, 2)))
    #model.add(Dropout(rate = 0.2))





    model.add(Flatten())

    model.add(Dense(units = 128, activation = 'relu'))
    #model.add(Dropout(rate = 0.1))
    model.add(Dense(units = 64, activation = 'relu'))
    model.add(Dropout(rate = 0.4))


    model.add(Dense(units = len(set(training_data.classes)), activation = 'sigmoid'))

    model.compile(optimizer = optimizer, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
    return model




model = KerasClassifier(build_fn=make_model)
optimizers = ['rmsprop', 'adam']
init = ['glorot_uniform', 'normal', 'uniform']
epochs = np.array([50, 100, 150])
batches = np.array([5, 10, 20])
param_grid = dict(optimizer=optimizers, nb_epoch=epochs, batch_size=batches, init=init)
grid = GridSearchCV(estimator=model, param_grid=param_grid)
grid_result = grid.fit(training_data)

In [ ]:

model = Sequential()

model.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu', input_shape = training_data.image_shape))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Dropout(rate = 0.4))

model.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Dropout(rate = 0.1))

#model.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu'))
#model.add(MaxPooling2D(pool_size = (2, 2)))
#model.add(Dropout(rate = 0.1))





model.add(Flatten())

model.add(Dense(units = 32, activation = 'relu'))
model.add(Dropout(rate = 0.5))
model.add(Dense(units = 16,activation = 'relu'))
model.add(Dropout(rate = 0.5))


model.add(Dense(units = len(set(training_data.classes)), activation = 'softmax'))
#model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])




classifier = KerasClassifier(build_fn=make_model)

optimizer = ['adam','rmsprop']
epochs = [15,25,30]
steps_per_epoch = [20,30]
validation_steps = [20,30]

param_grid = dict(epochs=epochs,steps_per_epoch = steps_per_epoch,validation_steps = validation_steps,
                 optimizer = optimizer)
grid = GridSearchCV(estimator=classifier, param_grid=param_grid, n_jobs=-1, cv=3, scoring = ['accuracy'],refit = False)
grid_result = grid.fit(training_data, testing_data)


In [ ]:
model.summary()

In [ ]:
fitted_model = model.fit_generator(training_data,
                        steps_per_epoch = 40,
                        epochs = 20,
                        validation_data = testing_data)

### to load and fit

import tensorflow as tf 
from keras.callbacks import History 

model = tf.keras.models.load_model('my_model.h5')

model.load_weights('model_num.h5')


fitted_model = model.fit_generator(training_data,
                        steps_per_epoch = 22,
                        epochs = 5,
                        validation_data = testing_data,
                        validation_steps = 12)

In [ ]:
# plotting accuracy and validation accuracy
accuracy = fitted_model.history['acc']
plt.plot(range(len(accuracy)), accuracy, 'bo', label = 'accuracy')
plt.legend()

from matplotlib import pyplot as plt
import cv2


imgCat = cv2.imread('C:/Users/asa_f/SJSU/257/project/300x300/more test/underpass1.jpg')
plt.imshow(imgCat)

imgCat = cv2.resize(imgCat, (300,300))
imgCat = imgCat.reshape(1,300,300,3)

pred = model.predict(imgCat)
print("Probability that it is a Cat = ", "%.2f" % (1-pred))

In [12]:
# testing the model
def testing_image(image_directory):

    test_image = image.load_img(image_directory, target_size = (100, 100))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = loaded_model.predict(x = test_image)
    print(result)
    if result[0][0]  >= 0.5:
        prediction = 'wall'
    else:
        prediction = 'underpass'
    return prediction

In [13]:
direc = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/more test'


for i in os.listdir(direc):

    image_file = Image.open(direc + '/' + i) # open colour image
    image_file = image_file.convert('1') # convert image to black and white
    image_file.save('C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/' + i)

In [14]:
from keras.preprocessing import image

In [15]:
for im in os.listdir(direc):
    
    #print('C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/' + im)

    preds = testing_image('C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/' + im)
    print("Prediction of the image named {} is {}.".format(im,preds))

[[0. 1.]]
Prediction of the image named underpass1.jpg is underpass.
[[0. 1.]]
Prediction of the image named underpass2.jpg is underpass.
[[0. 1.]]
Prediction of the image named underpass3.jpg is underpass.
[[0. 1.]]
Prediction of the image named underpass4.jpg is underpass.
[[0. 1.]]
Prediction of the image named underpass5.jpg is underpass.
[[1. 0.]]
Prediction of the image named wall1.png is wall.
[[1. 0.]]
Prediction of the image named wall2.png is wall.
[[1. 0.]]
Prediction of the image named wall3.png is wall.
[[1. 0.]]
Prediction of the image named wall4.png is wall.


## Save and Load Model

In [ ]:
model.save('cnn_75.h5')

In [ ]:
# serialize model to JSON
#  the keras model which is trained is defined as 'model' in this example
model_json = model.to_json()


with open("cnn_75_num.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("cnn_75_num.h5")

In [7]:
from keras.models import model_from_json
from keras.models import load_model
import keras
import tensorflow as tf 


In [8]:
loaded_model = tf.keras.models.load_model('cnn_75.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [9]:
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 98, 98, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 49, 49, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 49, 49, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 47, 47, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 23, 23, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 23, 23, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 16928)             0

In [10]:
loaded_model.load_weights('cnn_75_num.h5')

In [11]:
fitted_model = loaded_model.fit_generator(training_data,
                        steps_per_epoch = 40,
                        epochs = 2,
                        validation_data = testing_data)

Epoch 1/2
40/40 [==============================] - 6s 160ms/step - loss: 0.3175 - acc: 0.8699 - val_loss: 0.1754 - val_acc: 0.9392
Epoch 2/2
40/40 [==============================] - 6s 153ms/step - loss: 0.3066 - acc: 0.8958 - val_loss: 0.1858 - val_acc: 0.9527


In [ ]:
image1 = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/wall1.png'
image2 = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/underpass2.jpg'
image3 = 'C:/Users/asa_f/Desktop/SJSU/257/Project/Final Data/Final Data/blacknwhite/underpass1.jpg'

In [ ]:
loaded_model.predict_classes("your_test_data here")

https://www.kaggle.com/uysimty/keras-cnn-dog-or-cat-classification